// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPM.Infrastructure.Data;

#nullable disable

namespace PPM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PPM.Core.Entities.CreditCustomer", b =>
                {
                    b.Property<Guid>("CreditCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PaymentTermDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleNumbers")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("CreditCustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "IsBlocked");

                    b.HasIndex("TenantId", "Phone");

                    b.ToTable("CreditCustomers");
                });

            modelBuilder.Entity("PPM.Core.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("CreditTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CreditCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FuelSaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CreditTransactionId");

                    b.HasIndex("CreditCustomerId");

                    b.HasIndex("FuelSaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("PPM.Core.Entities.Expense", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("Category");

                    b.HasIndex("ExpenseDate");

                    b.HasIndex("RecordedById");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Category");

                    b.HasIndex("TenantId", "ExpenseDate");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PPM.Core.Entities.Feature", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeatureId");

                    b.HasIndex("FeatureCode")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8044),
                            Description = "Access to sales reports, dashboards, and analytics",
                            DisplayOrder = 1,
                            FeatureCode = "REPORTS",
                            FeatureName = "Reports & Analytics",
                            Icon = "chart-bar",
                            IsActive = true,
                            Module = "Analytics",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8047)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8055),
                            Description = "Manage credit customers and their balances",
                            DisplayOrder = 2,
                            FeatureCode = "CREDIT_CUSTOMERS",
                            FeatureName = "Credit Customer Management",
                            Icon = "credit-card",
                            IsActive = true,
                            Module = "Sales",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8055)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8059),
                            Description = "Track and manage business expenses",
                            DisplayOrder = 3,
                            FeatureCode = "EXPENSES",
                            FeatureName = "Expense Tracking",
                            Icon = "receipt",
                            IsActive = true,
                            Module = "Finance",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8060)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8063),
                            Description = "Support for multiple shifts per day",
                            DisplayOrder = 4,
                            FeatureCode = "MULTI_SHIFT",
                            FeatureName = "Multiple Shifts",
                            Icon = "clock",
                            IsActive = true,
                            Module = "Operations",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8064)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8067),
                            Description = "Export data to Excel and PDF",
                            DisplayOrder = 5,
                            FeatureCode = "EXPORT",
                            FeatureName = "Data Export",
                            Icon = "download",
                            IsActive = true,
                            Module = "Utilities",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8068)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8071),
                            Description = "Programmatic API access for integrations",
                            DisplayOrder = 6,
                            FeatureCode = "API_ACCESS",
                            FeatureName = "API Access",
                            Icon = "code",
                            IsActive = true,
                            Module = "Integration",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8072)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8093),
                            Description = "Advanced analytics and custom reports",
                            DisplayOrder = 7,
                            FeatureCode = "ADVANCED_REPORTS",
                            FeatureName = "Advanced Reports",
                            Icon = "chart-pie",
                            IsActive = true,
                            Module = "Analytics",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8094)
                        },
                        new
                        {
                            FeatureId = new Guid("f0000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8097),
                            Description = "Bulk import/export and batch operations",
                            DisplayOrder = 8,
                            FeatureCode = "BULK_OPERATIONS",
                            FeatureName = "Bulk Operations",
                            Icon = "database",
                            IsActive = true,
                            Module = "Utilities",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(8098)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelRate", b =>
                {
                    b.Property<Guid>("FuelRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("FuelRateId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("FuelTypeId", "EffectiveTo");

                    b.ToTable("FuelRates");

                    b.HasData(
                        new
                        {
                            FuelRateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9307),
                            EffectiveFrom = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(7926),
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rate = 102.50m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9309),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            FuelRateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9327),
                            EffectiveFrom = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9324),
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Rate = 89.75m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9328),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            FuelRateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9334),
                            EffectiveFrom = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9333),
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Rate = 75.00m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(9335),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelSale", b =>
                {
                    b.Property<Guid>("FuelSaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsVoided")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaleTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoidedBy")
                        .HasColumnType("text");

                    b.HasKey("FuelSaleId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex("SaleTime");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TenantId");

                    b.ToTable("FuelSales");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.Property<Guid>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FuelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Liters");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FuelTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "FuelCode")
                        .IsUnique();

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1121),
                            FuelCode = "PTR",
                            FuelName = "Petrol",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Liters",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1134)
                        },
                        new
                        {
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1155),
                            FuelCode = "DSL",
                            FuelName = "Diesel",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Liters",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1156)
                        },
                        new
                        {
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1160),
                            FuelCode = "CNG",
                            FuelName = "CNG",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 186, DateTimeKind.Utc).AddTicks(1161)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MachineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "MachineCode")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(3848),
                            InstallationDate = new DateOnly(2023, 1, 15),
                            IsActive = true,
                            Location = "Left Side",
                            MachineCode = "M001",
                            MachineName = "Machine 1",
                            Manufacturer = "Tokheim",
                            Model = "Premier B",
                            SerialNumber = "SRL-M1-2023",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(3849)
                        },
                        new
                        {
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(3865),
                            InstallationDate = new DateOnly(2023, 3, 20),
                            IsActive = true,
                            Location = "Right Side",
                            MachineCode = "M002",
                            MachineName = "Machine 2",
                            Manufacturer = "Wayne",
                            Model = "Helix 6000",
                            SerialNumber = "SRL-M2-2023",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(3866)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Nozzle", b =>
                {
                    b.Property<Guid>("NozzleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentMeterReading")
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("NozzleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NozzleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NozzleId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("MachineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "MachineId", "NozzleNumber")
                        .IsUnique();

                    b.ToTable("Nozzles");

                    b.HasData(
                        new
                        {
                            NozzleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6405),
                            CurrentMeterReading = 15234.567m,
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            NozzleName = "Petrol Nozzle 1",
                            NozzleNumber = "N1",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6406)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6421),
                            CurrentMeterReading = 23456.789m,
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsActive = true,
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            NozzleName = "Diesel Nozzle 1",
                            NozzleNumber = "N2",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6422)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6428),
                            CurrentMeterReading = 18765.432m,
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            NozzleName = "Petrol Nozzle 2",
                            NozzleNumber = "N1",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6428)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6434),
                            CurrentMeterReading = 5678.123m,
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsActive = true,
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            NozzleName = "CNG Nozzle 1",
                            NozzleNumber = "N2",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 187, DateTimeKind.Utc).AddTicks(6435)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.PlanFeature", b =>
                {
                    b.Property<Guid>("PlanFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlanFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("SubscriptionPlan", "FeatureId")
                        .IsUnique();

                    b.ToTable("PlanFeatures");

                    b.HasData(
                        new
                        {
                            PlanFeatureId = new Guid("ba000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9827),
                            FeatureId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9828)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9834),
                            FeatureId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9835)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9848),
                            FeatureId = new Guid("f0000003-0000-0000-0000-000000000003"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9849)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9853),
                            FeatureId = new Guid("f0000004-0000-0000-0000-000000000004"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9853)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9862),
                            FeatureId = new Guid("f0000005-0000-0000-0000-000000000005"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9863)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9867),
                            FeatureId = new Guid("f0000006-0000-0000-0000-000000000006"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9867)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9871),
                            FeatureId = new Guid("f0000007-0000-0000-0000-000000000007"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9872)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ba000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9875),
                            FeatureId = new Guid("f0000008-0000-0000-0000-000000000008"),
                            IsEnabled = false,
                            SubscriptionPlan = "Basic",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 189, DateTimeKind.Utc).AddTicks(9875)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(67),
                            FeatureId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            IsEnabled = true,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(68)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(71),
                            FeatureId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            IsEnabled = true,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(72)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(76),
                            FeatureId = new Guid("f0000003-0000-0000-0000-000000000003"),
                            IsEnabled = true,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(76)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(80),
                            FeatureId = new Guid("f0000004-0000-0000-0000-000000000004"),
                            IsEnabled = true,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(80)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(84),
                            FeatureId = new Guid("f0000005-0000-0000-0000-000000000005"),
                            IsEnabled = true,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(85)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(88),
                            FeatureId = new Guid("f0000006-0000-0000-0000-000000000006"),
                            IsEnabled = false,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(89)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(92),
                            FeatureId = new Guid("f0000007-0000-0000-0000-000000000007"),
                            IsEnabled = false,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(93)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("ca000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(96),
                            FeatureId = new Guid("f0000008-0000-0000-0000-000000000008"),
                            IsEnabled = false,
                            SubscriptionPlan = "Premium",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(97)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(152),
                            FeatureId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(153)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(156),
                            FeatureId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(157)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(160),
                            FeatureId = new Guid("f0000003-0000-0000-0000-000000000003"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(161)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(164),
                            FeatureId = new Guid("f0000004-0000-0000-0000-000000000004"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(165)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(168),
                            FeatureId = new Guid("f0000005-0000-0000-0000-000000000005"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(169)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(172),
                            FeatureId = new Guid("f0000006-0000-0000-0000-000000000006"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(173)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(176),
                            FeatureId = new Guid("f0000007-0000-0000-0000-000000000007"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(177)
                        },
                        new
                        {
                            PlanFeatureId = new Guid("da000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(180),
                            FeatureId = new Guid("f0000008-0000-0000-0000-000000000008"),
                            IsEnabled = true,
                            SubscriptionPlan = "Enterprise",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 190, DateTimeKind.Utc).AddTicks(181)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Borrowing")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CashCollected")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DigitalPayments")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Variance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("ShiftId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("PPM.Core.Entities.ShiftNozzleReading", b =>
                {
                    b.Property<Guid>("ShiftNozzleReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ClosingReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OpeningReading")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("QuantitySold")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("RateAtShift")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShiftNozzleReadingId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ShiftId", "NozzleId")
                        .IsUnique();

                    b.ToTable("ShiftNozzleReadings");
                });

            modelBuilder.Entity("PPM.Core.Entities.StockEntry", b =>
                {
                    b.Property<Guid>("StockEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FuelSaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("StockBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("StockEntryId");

                    b.HasIndex("EntryDate");

                    b.HasIndex("EntryType");

                    b.HasIndex("FuelSaleId");

                    b.HasIndex("RecordedById");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ShiftId");

                    b.HasIndex("TenantId", "TankId", "EntryDate");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("PPM.Core.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SuperAdmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SystemUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SystemUsers");

                    b.HasData(
                        new
                        {
                            SystemUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 586, DateTimeKind.Utc).AddTicks(5110),
                            Email = "admin@ppmapp.com",
                            FullName = "Super Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$bV6OIM2Y8wUJST5L6yazSOQRjpUSFcjG/dvVDKiW76svIAbae033m",
                            Role = "SuperAdmin",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 586, DateTimeKind.Utc).AddTicks(5294),
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Tank", b =>
                {
                    b.Property<Guid>("TankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastCalibrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("MinimumLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("TankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TankId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "FuelTypeId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "TankCode")
                        .IsUnique();

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("PPM.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("India");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxMachines")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonthlyBills")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWorkers")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.HasIndex("SubscriptionStatus", "IsActive");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "123 Demo Street, Near City Center",
                            City = "Mumbai",
                            CompanyName = "Demo Petrol Pump",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 587, DateTimeKind.Utc).AddTicks(8355),
                            Email = "demo@petroldemo.com",
                            IsActive = true,
                            MaxMachines = 5,
                            MaxMonthlyBills = 10000,
                            MaxWorkers = 20,
                            OwnerName = "Rajesh Kumar",
                            Phone = "9876543210",
                            PinCode = "400001",
                            State = "Maharashtra",
                            SubscriptionEndDate = new DateTime(2027, 1, 9, 6, 10, 50, 587, DateTimeKind.Utc).AddTicks(5584),
                            SubscriptionPlan = "Premium",
                            SubscriptionStartDate = new DateTime(2026, 1, 9, 6, 10, 50, 587, DateTimeKind.Utc).AddTicks(5465),
                            SubscriptionStatus = "Active",
                            TenantCode = "DEMO001",
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 587, DateTimeKind.Utc).AddTicks(8357)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.TenantFeature", b =>
                {
                    b.Property<Guid>("TenantFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OverriddenBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("TenantId", "FeatureId")
                        .IsUnique();

                    b.ToTable("TenantFeatures");
                });

            modelBuilder.Entity("PPM.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "Phone")
                        .IsUnique();

                    b.HasIndex("TenantId", "Role");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 770, DateTimeKind.Utc).AddTicks(7584),
                            Email = "owner@petroldemo.com",
                            FullName = "Rajesh Kumar",
                            IsActive = true,
                            PasswordHash = "$2a$11$jtnPnZLbP04J9085SWqQdurF2UA/7a9VCre34UUOg5bd5u3IlLavu",
                            Phone = "9876543210",
                            Role = "Owner",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 770, DateTimeKind.Utc).AddTicks(7595),
                            Username = "owner"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 935, DateTimeKind.Utc).AddTicks(3278),
                            DateOfJoining = new DateTime(2025, 7, 9, 6, 10, 50, 935, DateTimeKind.Utc).AddTicks(2213),
                            Email = "manager@petroldemo.com",
                            EmployeeCode = "MGR001",
                            FullName = "Suresh Patel",
                            IsActive = true,
                            PasswordHash = "$2a$11$lsXspL/8haOyyySgQ8.ZgeLRiVkswrG/V.JQQPuA.aneJVQvv8Kuu",
                            Phone = "9876543211",
                            Role = "Manager",
                            Salary = 30000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 50, 935, DateTimeKind.Utc).AddTicks(3281),
                            Username = "manager"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 61, DateTimeKind.Utc).AddTicks(3901),
                            DateOfJoining = new DateTime(2025, 10, 9, 6, 10, 51, 61, DateTimeKind.Utc).AddTicks(3874),
                            Email = "ramesh@petroldemo.com",
                            EmployeeCode = "EMP001",
                            FullName = "Ramesh Kumar",
                            IsActive = true,
                            PasswordHash = "$2a$11$tvtbMwtMwyuhaAbGbRgzQunCS7h.y1CGu0uVUSz5rfsQfyrXHc9hO",
                            Phone = "9876543212",
                            Role = "Worker",
                            Salary = 15000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 61, DateTimeKind.Utc).AddTicks(3904),
                            Username = "ramesh"
                        },
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 185, DateTimeKind.Utc).AddTicks(911),
                            DateOfJoining = new DateTime(2025, 11, 9, 6, 10, 51, 185, DateTimeKind.Utc).AddTicks(885),
                            Email = "dinesh@petroldemo.com",
                            EmployeeCode = "EMP002",
                            FullName = "Dinesh Sharma",
                            IsActive = true,
                            PasswordHash = "$2a$11$48bo9mIxLIwW6cptXE7DYukH1Y4gbFczWk3SwvTM2ZvQzuL6fCeZK",
                            Phone = "9876543213",
                            Role = "Worker",
                            Salary = 15000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 9, 6, 10, 51, 185, DateTimeKind.Utc).AddTicks(914),
                            Username = "dinesh"
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.CreditCustomer", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.CreditTransaction", b =>
                {
                    b.HasOne("PPM.Core.Entities.CreditCustomer", "CreditCustomer")
                        .WithMany("Transactions")
                        .HasForeignKey("CreditCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.FuelSale", "FuelSale")
                        .WithMany()
                        .HasForeignKey("FuelSaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCustomer");

                    b.Navigation("FuelSale");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Expense", b =>
                {
                    b.HasOne("PPM.Core.Entities.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedBy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelRate", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelType", "FuelType")
                        .WithMany("FuelRates")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FuelType");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelSale", b =>
                {
                    b.HasOne("PPM.Core.Entities.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Shift", "Shift")
                        .WithMany("FuelSales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Nozzle", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Machine", "Machine")
                        .WithMany("Nozzles")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");

                    b.Navigation("Machine");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.PlanFeature", b =>
                {
                    b.HasOne("PPM.Core.Entities.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("PPM.Core.Entities.Shift", b =>
                {
                    b.HasOne("PPM.Core.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.User", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Tenant");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("PPM.Core.Entities.ShiftNozzleReading", b =>
                {
                    b.HasOne("PPM.Core.Entities.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Shift", "Shift")
                        .WithMany("NozzleReadings")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.StockEntry", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelSale", "FuelSale")
                        .WithMany()
                        .HasForeignKey("FuelSaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PPM.Core.Entities.User", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PPM.Core.Entities.Tank", "Tank")
                        .WithMany("StockEntries")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelSale");

                    b.Navigation("RecordedBy");

                    b.Navigation("Shift");

                    b.Navigation("Tank");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Tank", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.TenantFeature", b =>
                {
                    b.HasOne("PPM.Core.Entities.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.User", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.CreditCustomer", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.Navigation("FuelRates");
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("PPM.Core.Entities.Shift", b =>
                {
                    b.Navigation("FuelSales");

                    b.Navigation("NozzleReadings");
                });

            modelBuilder.Entity("PPM.Core.Entities.Tank", b =>
                {
                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("PPM.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
