// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPM.Infrastructure.Data;

#nullable disable

namespace PPM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PPM.Core.Entities.FuelRate", b =>
                {
                    b.Property<Guid>("FuelRateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("FuelRateId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("FuelTypeId", "EffectiveTo");

                    b.ToTable("FuelRates");

                    b.HasData(
                        new
                        {
                            FuelRateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7859),
                            EffectiveFrom = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7149),
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Rate = 102.50m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7860),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            FuelRateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7866),
                            EffectiveFrom = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7865),
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Rate = 89.75m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7867),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            FuelRateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7871),
                            EffectiveFrom = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7870),
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            Rate = 75.00m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(7871),
                            UpdatedBy = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.Property<Guid>("FuelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FuelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Liters");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FuelTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "FuelCode")
                        .IsUnique();

                    b.ToTable("FuelTypes");

                    b.HasData(
                        new
                        {
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5826),
                            FuelCode = "PTR",
                            FuelName = "Petrol",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Liters",
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5828)
                        },
                        new
                        {
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5835),
                            FuelCode = "DSL",
                            FuelName = "Diesel",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Liters",
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5835)
                        },
                        new
                        {
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5837),
                            FuelCode = "CNG",
                            FuelName = "CNG",
                            IsActive = true,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Unit = "Kg",
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(5838)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MachineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "MachineCode")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(600),
                            InstallationDate = new DateOnly(2023, 1, 15),
                            IsActive = true,
                            Location = "Left Side",
                            MachineCode = "M001",
                            MachineName = "Machine 1",
                            Manufacturer = "Tokheim",
                            Model = "Premier B",
                            SerialNumber = "SRL-M1-2023",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(601)
                        },
                        new
                        {
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(610),
                            InstallationDate = new DateOnly(2023, 3, 20),
                            IsActive = true,
                            Location = "Right Side",
                            MachineCode = "M002",
                            MachineName = "Machine 2",
                            Manufacturer = "Wayne",
                            Model = "Helix 6000",
                            SerialNumber = "SRL-M2-2023",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(610)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Nozzle", b =>
                {
                    b.Property<Guid>("NozzleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentMeterReading")
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("NozzleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NozzleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NozzleId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("MachineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "MachineId", "NozzleNumber")
                        .IsUnique();

                    b.ToTable("Nozzles");

                    b.HasData(
                        new
                        {
                            NozzleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2019),
                            CurrentMeterReading = 15234.567m,
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            NozzleName = "Petrol Nozzle 1",
                            NozzleNumber = "N1",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2019)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2026),
                            CurrentMeterReading = 23456.789m,
                            FuelTypeId = new Guid("88888888-8888-8888-8888-888888888888"),
                            IsActive = true,
                            MachineId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            NozzleName = "Diesel Nozzle 1",
                            NozzleNumber = "N2",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2026)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2029),
                            CurrentMeterReading = 18765.432m,
                            FuelTypeId = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            NozzleName = "Petrol Nozzle 2",
                            NozzleNumber = "N1",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2029)
                        },
                        new
                        {
                            NozzleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2032),
                            CurrentMeterReading = 5678.123m,
                            FuelTypeId = new Guid("99999999-9999-9999-9999-999999999999"),
                            IsActive = true,
                            MachineId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            NozzleName = "CNG Nozzle 1",
                            NozzleNumber = "N2",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 896, DateTimeKind.Utc).AddTicks(2033)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("SystemUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SuperAdmin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SystemUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SystemUsers");

                    b.HasData(
                        new
                        {
                            SystemUserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 118, DateTimeKind.Utc).AddTicks(7596),
                            Email = "admin@ppmapp.com",
                            FullName = "Super Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$IAZW0nQU4pHQcssG0pdgxuXNhsRTRaHFe7hVC9lJQwwKC.XbZ1KqW",
                            Role = "SuperAdmin",
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 118, DateTimeKind.Utc).AddTicks(7847),
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("India");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxMachines")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonthlyBills")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWorkers")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantCode")
                        .IsUnique();

                    b.HasIndex("SubscriptionStatus", "IsActive");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "123 Demo Street, Near City Center",
                            City = "Mumbai",
                            CompanyName = "Demo Petrol Pump",
                            Country = "India",
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 119, DateTimeKind.Utc).AddTicks(9982),
                            Email = "demo@petroldemo.com",
                            IsActive = true,
                            MaxMachines = 5,
                            MaxMonthlyBills = 10000,
                            MaxWorkers = 20,
                            OwnerName = "Rajesh Kumar",
                            Phone = "9876543210",
                            PinCode = "400001",
                            State = "Maharashtra",
                            SubscriptionEndDate = new DateTime(2027, 1, 6, 17, 56, 47, 119, DateTimeKind.Utc).AddTicks(9105),
                            SubscriptionPlan = "Premium",
                            SubscriptionStartDate = new DateTime(2026, 1, 6, 17, 56, 47, 119, DateTimeKind.Utc).AddTicks(8947),
                            SubscriptionStatus = "Active",
                            TenantCode = "DEMO001",
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 119, DateTimeKind.Utc).AddTicks(9983)
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "Phone")
                        .IsUnique();

                    b.HasIndex("TenantId", "Role");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 374, DateTimeKind.Utc).AddTicks(6210),
                            Email = "owner@petroldemo.com",
                            FullName = "Rajesh Kumar",
                            IsActive = true,
                            PasswordHash = "$2a$11$X/9IBFn0Tmn6SqVVqmsSl.LPU3CCwXRgacwz696HToBhi1SA4wckW",
                            Phone = "9876543210",
                            Role = "Owner",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 374, DateTimeKind.Utc).AddTicks(6219),
                            Username = "owner"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 616, DateTimeKind.Utc).AddTicks(6813),
                            DateOfJoining = new DateTime(2025, 7, 6, 17, 56, 47, 616, DateTimeKind.Utc).AddTicks(5643),
                            Email = "manager@petroldemo.com",
                            EmployeeCode = "MGR001",
                            FullName = "Suresh Patel",
                            IsActive = true,
                            PasswordHash = "$2a$11$erBYpjJblLycx54Poslw5ukpuTAVuVMXwUq3K2PaUx8exyLm5cPvy",
                            Phone = "9876543211",
                            Role = "Manager",
                            Salary = 30000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 616, DateTimeKind.Utc).AddTicks(6817),
                            Username = "manager"
                        },
                        new
                        {
                            UserId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 754, DateTimeKind.Utc).AddTicks(8492),
                            DateOfJoining = new DateTime(2025, 10, 6, 17, 56, 47, 754, DateTimeKind.Utc).AddTicks(8471),
                            Email = "ramesh@petroldemo.com",
                            EmployeeCode = "EMP001",
                            FullName = "Ramesh Kumar",
                            IsActive = true,
                            PasswordHash = "$2a$11$gp0JbMF9CJccBTCTXd84AutJsRg/f5Kp7pE1PRHjZQOxAXS8zx95i",
                            Phone = "9876543212",
                            Role = "Worker",
                            Salary = 15000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 754, DateTimeKind.Utc).AddTicks(8496),
                            Username = "ramesh"
                        },
                        new
                        {
                            UserId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(2188),
                            DateOfJoining = new DateTime(2025, 11, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(2053),
                            Email = "dinesh@petroldemo.com",
                            EmployeeCode = "EMP002",
                            FullName = "Dinesh Sharma",
                            IsActive = true,
                            PasswordHash = "$2a$11$16p/gZ1czTJyC208WL/QtOGMdr19vxPqr6B.0m3S3fpQb/1K8Q4LS",
                            Phone = "9876543213",
                            Role = "Worker",
                            Salary = 15000m,
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 6, 17, 56, 47, 895, DateTimeKind.Utc).AddTicks(2193),
                            Username = "dinesh"
                        });
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelRate", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelType", "FuelType")
                        .WithMany("FuelRates")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FuelType");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.Nozzle", b =>
                {
                    b.HasOne("PPM.Core.Entities.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Machine", "Machine")
                        .WithMany("Nozzles")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelType");

                    b.Navigation("Machine");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.User", b =>
                {
                    b.HasOne("PPM.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PPM.Core.Entities.FuelType", b =>
                {
                    b.Navigation("FuelRates");
                });

            modelBuilder.Entity("PPM.Core.Entities.Machine", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("PPM.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
