using PPM.Core.Common;

namespace PPM.Core.Entities;

/// <summary>
/// License keys for subscription activation
/// Generated by Super Admin and activated by tenant owners
/// </summary>
public class LicenseKey : BaseEntity
{
    public Guid LicenseKeyId { get; set; }

    /// <summary>
    /// Unique license key in format: PPM-XXXX-XXXX-XXXX-XXXX
    /// </summary>
    public string Key { get; set; } = string.Empty;

    // License details
    public string SubscriptionPlan { get; set; } = "Basic"; // Basic, Premium, Enterprise
    public int DurationMonths { get; set; } = 12;

    // Limits (copied to tenant on activation)
    public int MaxMachines { get; set; } = 5;
    public int MaxWorkers { get; set; } = 20;
    public int MaxMonthlyBills { get; set; } = 10000;

    // Status
    public string Status { get; set; } = "Available"; // Available, Used, Revoked

    // Usage tracking
    public Guid? ActivatedByTenantId { get; set; }
    public DateTime? ActivatedAt { get; set; }

    // Admin tracking
    public Guid GeneratedBySystemUserId { get; set; }
    public string? Notes { get; set; }

    // Navigation properties
    public virtual Tenant? ActivatedByTenant { get; set; }
    public virtual SystemUser GeneratedBySystemUser { get; set; } = null!;
}
